---
minimum_pre_commit_version: 2.18.1
exclude: ^(dist|build)
repos:

# commit-msg hooks
# ----------

# Conventional Commit message checker (commitizen)
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.23.0
  hooks:
  - id: commitizen
    stages:
    - commit-msg

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
# Protocol buffer linting
- repo: https://github.com/yoheimuta/protolint
  rev: v0.37.1
  hooks:
  - id: protolint
