---
name: publish

# Actions for any tag.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# At the GitHub 'organisation' or 'project' level you must have the following
# GitHub 'Repository Secrets' defined (i.e. via 'Settings -> Secrets'): -
#
# PYPI_USERNAME
# PYPI_TOKEN
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (none)

on:
  push:
    tags:
    - '**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.17.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        pip install -r build-requirements.txt
    - name: Build
      env:
        P_BASE: 'src/main/proto'
        DM_PATH: 'informaticsmatters/protobuf/datamanager'
      run: |
        pyroma .
        protoc -I=${P_BASE} --python_out=${P_BASE} ${P_BASE}/${DM_PATH}/*.proto
        touch ${P_BASE}/informaticsmatters/protobuf/__init__.py
        touch ${P_BASE}/${DM_PATH}/__init__.py
        python -m build --sdist --wheel --outdir dist/
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_TOKEN }}
